### ISSUE TITLE
The question about output of 'monte_carlo_forward'

### ISSUE THREAD

**Issue by dream-chaser** [tjiiv-cprg/EPro-PnP#10]
hello, thanks for your source code firstly.
i want to know what is the difference between "pose_opt" and "pose_opt_plus"
if i want to use pose in my own loss, which one should i pick ?
thanks for your answer !

`
        return pose_opt, cost, pose_opt_plus, pose_samples, pose_sample_logweights, cost_init
`

**Comment by Lakonik** [comment]
Hi! pose_opt corresponds to y* in the paper, which is the PnP solution and can not be backpropagated (as we don't use implicit differentiation). pose_opt_plus corresponds to y* + Δy, which is used for derivative regularization loss. You can refer to this [demo](https://github.com/tjiiv-cprg/EPro-PnP/blob/main/demo/fit_identity.ipynb) for more details.
