### ISSUE TITLE
Test Accuracy all zeros

### ISSUE THREAD

**Issue by jiangziben** [tjiiv-cprg/EPro-PnP#11]
hello, i use your trained model to test  6D pose estimate in linemod dataset, but i find all the accuracies are  zeros and none. what's wrong with my code?    
![Screenshot from 2022-07-02 17-55-29](https://user-images.githubusercontent.com/26041334/176995687-d26e218e-aedd-4da6-b40a-34dec42b11ef.png)
![Screenshot from 2022-07-02 17-55-17](https://user-images.githubusercontent.com/26041334/176995693-5a81146d-46af-4d50-b404-5f314682a502.png)

**Comment by Lakonik** [comment]
Hi! Please post the complete output for diagnosis. I think it is possible that you loaded the wrong model (e.g. cdpn_stage_1.pth).

**Comment by jiangziben** [comment]
Thank you for your reply, i have got the right output.
