### ISSUE TITLE
About the alternative softmax

### ISSUE THREAD

**Issue by aragakiyui611** [tjiiv-cprg/EPro-PnP#16]
https://github.com/tjiiv-cprg/EPro-PnP/blob/209727638ea992d53275a075c95c316182c01efd/EPro-PnP-6DoF/lib/train.py#L163
Why use an alternative of SoftMax instead of original one? 
Thank you every much!

**Comment by Lakonik** [comment]
This is basically a legacy design choice. In an early experiment we found that this alternative version performed slightly better than standard Softmax, although the difference seems too trivial as validated by some later experiments.

Generally we recommend using the standard Softmax as it is more numerically stable.
