### ISSUE TITLE
Errors when training with CDPN init.

### ISSUE THREAD

**Issue by Tangshitao** [tjiiv-cprg/EPro-PnP#17]
Hi, I encounter an error when training using cdpn init config.

_, R_vector, T_vector = cv2.solvePnP(                                                                                                      
IndexError: boolean index did not match indexed array along dimension 1; dimension is 64 but corresponding boolean dimension is 2 

The error codes are
`_, R_vector, T_vector = cv2.solvePnP(
                    x3d_np_[mask_np_], x2d_np_[mask_np_], cam_intrinsic_np, dist_coeffs, flags=cv2.SOLVEPNP_EPNP)`

 Specifically:
`x3d_np_[mask_np_]`

**Comment by Lakonik** [comment]
Thanks for the feedback! This bug has been fixed now.
