### ISSUE TITLE
BOP related data

### ISSUE THREAD

**Issue by FabianSchuetze** [tjiiv-cprg/EPro-PnP#2]
Hi,
 
thanks for your wonderful paper - It's a pleasure to read!

Is there a way to download the BOP related data without a baidu account? I cannot register to their service because my cellphone number does not conform to the required format. If not, could you maybe describe the data layout in more detail, so that one assemble the data oneself ?

**Comment by Lakonik** [comment]
Thank your for your feedback! I have uploaded a copy of the dataset [here](https://mega.nz/folder/w0sTxbYa#0w-huVv5gK953mO-eGpYVg).

**Comment by FabianSchuetze** [comment]
Thanks for the reply. I have tried the test set which works very well - thanks!
