### ISSUE TITLE
一人血书，求一个docker！

### ISSUE THREAD

**Issue by zhustrong** [tjiiv-cprg/EPro-PnP#22]
楼主您好，这篇论文的思路太惊艳了，我非常想在自己的数据集上测试一下，但是环境配置了好几天都没能正常运行demo，能不能麻烦您帮忙开放了一个docker，万分感谢！！！

**Comment by Lakonik** [comment]
Thank you for the suggestion. I don't use docker very often, but I will consider it.

**Comment by zhustrong** [comment]
great appreciate !
