### ISSUE TITLE
请问如何将pth模型转换成onnx格式

### ISSUE THREAD

**Issue by Originval** [tjiiv-cprg/EPro-PnP#28]
我想把EPro-PnP-Det训练的模型转成onnx格式,但中途遇到了很多问题,希望能提供转换脚本帮助我快速找到问题所在,谢谢

**Comment by Lakonik** [comment]
Hi! Unfortunately ONNX export is not officially supported for now.

**Comment by Originval** [comment]
Ok, thank you for your excellent work.
