### ISSUE TITLE
discard file

### ISSUE THREAD

**Issue by legendship** [tjiiv-cprg/EPro-PnP#33]
I downloaded dataset sub-datasets "full dataset(v1.0)" and "Teaser dataset (v0.1) -- Deprecated" in "nuScenes" to pre-process the data.
When I run the follow code:"python tools/data_converter/nuscenes_converter.py data/nuscenes --version v1.0-trainval"
An error:"FileNotFoundError: file "data/nuscenes/samples/LIDAR_TOP/n015-2018-08-02-17-16-37+0800__LIDAR_TOP__1533201470448696.pcd.bin" does not exist
"
Please tell me how to slove it ? Thanks!

**Comment by Lakonik** [comment]
Hi! You don't need to download the teaser dataset. Only the keyframe blobs in the trainval set are required.

**Comment by legendship** [comment]
thank you very much！The former problem has been solved, The program is already running tonight. Thank you for your kindness！

**Comment by legendship** [comment]
hello author! when I running the code, an error occured "CUDA out of memory".
Please tell me how to set the batch_size, or some other methods to solve the problem？
