### ISSUE TITLE
A possible 'typo' in the code?

### ISSUE THREAD

**Issue by qinyq** [tjiiv-cprg/EPro-PnP#35]
The class name 'DefromPnPHead' would be 'DeformPnPHead', is that correct? :-P although it doesn't really affect anything at all...

**Comment by Lakonik** [comment]
Yeah, that's a good point. It's weird that I never noticed it...
Will fix it. Thanks!

**Comment by Lakonik** [comment]
Well it turns out that renaming this module would require renaming the parameters in the pretrained models too, which might cause some troubles for people using the old code. Maybe it's better not mess with the naming lol.
