### ISSUE TITLE
How to get Eq.(4) from DKL(t(y) || p(y|X)) in the paper

### ISSUE THREAD

**Issue by codeman-24** [tjiiv-cprg/EPro-PnP#36]
![image](https://user-images.githubusercontent.com/25739094/188398205-19d0693f-c6ab-42ea-97a5-c4c70fec8351.png)

**Comment by Lakonik** [comment]
Hi! This is derived from the definition of the KL divergence between t(y) and p(y|X). All you have to do is substitute Eq. (3) and drop the constant (t(y) is a fixed target so it can be treated as a constant).

**Comment by codeman-24** [comment]
![image](https://user-images.githubusercontent.com/25739094/188418241-e4f175f0-dd22-4a46-93ec-eb983feadf16.png)
Above is my derivation using KL formula.  Is there any convertion from this to Eq. (4) with p(X|y) and log\int p(X|y) ？

**Comment by Lakonik** [comment]
Note the difference between p(X|y) and p(y|X)

<div align="center"><img style="background: white;" src="https://latex.codecogs.com/svg.latex?%5Cbegin%7Baligned%7D%0D%0AD_%5Ctext%7BKL%7D%20%26%3D%20%5Cint%20t(y)%20%5Cleft(%5Clog%7Bt(y)%7D%20-%20%5Clog%7Bp(y%7CX)%7D%20%5Cright)%20%5Cmathrm%7Bd%7D%20y%20%5C%5C%0D%0A%26%3D%20-%5Cint%20t(y)%20%5Clog%7Bp(y%7CX)%7D%20%5Cmathrm%7Bd%7D%20y%20%2B%20const%20%5C%5C%0D%0A%26%3D%20-%5Cint%20t(y)%20%5Clog%20%5Cfrac%7Bp(X%7Cy)%7D%7B%5Cint%20p(X%7Cy)%20%5Cmathrm%7Bd%7D%20y%7D%20%5Cmathrm%7Bd%7D%20y%20%2B%20const%20%5C%5C%0D%0A%26%3D%20-%5Cint%20t(y)%20%5Clog%20p(X%7Cy)%5Cmathrm%7Bd%7D%20y%20%2B%20%5Cleft(%5Clog%20%5Cint%20p(X%7Cy)%20%5Cmathrm%7Bd%7D%20y%5Cright)%20%5Cint%20t(y)%20%5Cmathrm%7Bd%7D%20y%20%2B%20const%20%5C%5C%0D%0A%26%3D%20-%5Cint%20t(y)%20%5Clog%20p(X%7Cy)%5Cmathrm%7Bd%7D%20y%20%2B%20%5Clog%20%5Cint%20p(X%7Cy)%20%5Cmathrm%7Bd%7D%20y%20%2B%20const%20%0D%0A%5Cend%7Baligned%7D%0D"></div>

**Comment by codeman-24** [comment]
Thank you !!
