### ISSUE TITLE
sparse 2D-3D correspondse

### ISSUE THREAD

**Issue by hong-yang-Kai** [tjiiv-cprg/EPro-PnP#4]
Hello!For 6D pose estimation,if number of 2D-3D pairs is 8 , can  I use EPro-Pnp ?Due to certain reasons，dense 2D-3D correspondse is unavailable.

**Comment by Lakonik** [comment]
Yes, but I am not sure if 8 pairs are sufficient to achieve good results though, it depends on your problem.

**Comment by Lakonik** [comment]
Feel free to reopen if you have any question.
