### ISSUE TITLE
Questions about the Jacobian matrix 

### ISSUE THREAD

**Issue by lyj9494** [tjiiv-cprg/EPro-PnP#41]
Congratulations on winning the honor of cvpr2022 best student paper and thanks for sharing your work!

However, the computation of the Jacobian matrix confused me a lot.  In your code, 
https://github.com/tjiiv-cprg/EPro-PnP/blob/1545131fde2b47ec4c135776d575e11feeb0f7cd/epropnp/camera.py#L121

When the dof equals to 6, 
```
d_x3dcam_d_rot = skew(x3d_rot * 2)
jac = torch.cat((d_x2d_d_x3dcam, d_x2d_d_x3dcam @ d_x3dcam_d_rot), dim=-1)
```

Could you please tell me how do you get the Jacobian matrix? It’s a little difficult for me to understand the _d_x3dcam_d_rot_, and I wish your reply could help me to figure out why the x3d_rot should be multiplied by 2, and why only the rotation is considered.

Additionally, I referred to some materials when trying to compute the Jacobian matrix, for example, in this article [https://zhuanlan.zhihu.com/p/482540286](link), they compute the Jacobian matrix of the reprojection errors in this way:
<img width="919" alt="image" src="https://user-images.githubusercontent.com/91005527/191220183-23f635d3-5da9-4702-93c3-d9f9a12b0730.png">

I think if I follow this equation, the code should be
```
x3d_cam = x3d @ quaternion_to_rot_mat(pose[..., 3:]).transpose(-1, -2)+ pose[..., None, :3]
jac = torch.cat((d_x2d_d_x3dcam, d_x2d_d_x3dcam @ skew(x3d_cam)), dim=-1)
```

Which is different from your algorithm, and it puzzles me a lot. I am looking forward to your reply, and thank you again for your great job.

**Comment by Lakonik** [comment]
I did not follow the perturbation model mentioned in the article when writing the code. So perhaps our definition of orientation is different. The `d_rot` in this repo refers to a local delta in the 3D tangent space of the 4D quaternion hypersphere, and its conversion follows this transformation method:

https://github.com/tjiiv-cprg/EPro-PnP/blob/1545131fde2b47ec4c135776d575e11feeb0f7cd/epropnp/camera.py#L146

So our implementation is probably not standard practice, but still solves the problem.

**Comment by lyj9494** [comment]
Thank you for your patient reply !  Know I can figure out the difference between the two algorithms. Although  I have a better understanding of `d_x3dcam_d_rot`, I am still confused that why it equals to `skew(x3d_rot * 2)`, could you please tell me how to compute it?

**Comment by Lakonik** [comment]
Sorry but I did not write down the derivation of the Jacobian and I can't remember these details :(
But in fact it's not that difficult. You may try some symbolic math tools (like MATLAB) to get the results without doing it manually.

**Comment by lyj9494** [comment]
Thank you for your response !

**Comment by TruongKhang** [comment]
Hello @lyj9494 , I'm also confused about the Jacobian computation in the code. Did you figure out the answer to this?
