### ISSUE TITLE
Use EPro-PnP to replace EPnP

### ISSUE THREAD

**Issue by junshengzhou** [tjiiv-cprg/EPro-PnP#45]
Hi,
Thanks for your great job!
I have some questions about the performance of EPro-PnP, can I use EPro-PnP as a faster PnP solver to replace the traditional PnP(e.g. EPnP with Ransec by `cv2.solvePnPRansac`)?. 
I try to use EPro-PnP to replace the EPnP as a post-processing module to solve the 2D-3D registration problem(image to point cloud) , but I found that EPro-PnP performs well in easy mode but will cause large errors in difficult mode (with some false correspondences) while EPnP (with Ransec) can handle these false correspondences more robust. Can you give me some suggestions on how to avoid large errors? Thanks a lot.

**Comment by junshengzhou** [comment]
By the way, I don't use the weight so I just set w2d to be the same:
```
w2d = torch.ones_like(x2d)
w2d = (w2d.log_softmax(dim=-2) + self.log_weight_scale).exp()
```
Would that be a problem?

**Comment by Lakonik** [comment]
As a pure solver, using EPro-PnP (or just L-M optimization) without RANSAC may not be a good idea to handle the outliers, unless you adjust the kernel settings (currently we're using the Huber kernel, but you may try tuning the threshold parameter, or implement something else like the Cauchy kernel). But it would a lot better if the weights (w2d) are learned in an end-to-end fashion.

BTW, theoretically EPnP is a lot faster than L-M optimization, but practically it's a matter of efficient implementation (especially on GPU)

**Comment by junshengzhou** [comment]
Hi, 
Thanks for your timely reply and your notice on the efficiency of EPnP/L-M optimization! I have tried to reduce(or raise) the hyperparameter `relative_delta` in huber kernel but does't receive better results. 
I also use cv2.solvePnP(EPnP without Ransac) and find that the performance is similar to EPro-PnP on handling the outliers(false correspondences), so I guess the problem is the lack of Ransac. I wonder if it's possible to apply Ransac to EPro-PnP? Or should I just try to learn a better weights (or design a better kernel) to help handling the outliners?
Thanks again for your great job and kindly help!

**Comment by Lakonik** [comment]
L-M with RANSAC is possible. In fact our initialization method is basically just a generalization of RANSAC, but we don't filter any outliers in the final refinement step. You may try removing the outliers by hard thresholding just like RANSAC, or implement the Cauchy kernel which works like soft thresholding (I recommend the former which is easier and more efficient).

**Comment by junshengzhou** [comment]
Hi,
Thanks for your kindly help~ I will have a try on removing the outliers.

**Comment by zhirui-gao** [comment]
> L-M with RANSAC is possible. In fact our initialization method is basically just a generalization of RANSAC, but we don't filter any outliers in the final refinement step. You may try removing the outliers by hard thresholding just like RANSAC, or implement the Cauchy kernel which works like soft thresholding (I recommend the former which is easier and more efficient).


Hi, amazing work!  
I want to know whether you don't filter any outliers to achieve a differentiable process for a end-to-end trianing manner.

**Comment by Lakonik** [comment]
> > L-M with RANSAC is possible. In fact our initialization method is basically just a generalization of RANSAC, but we don't filter any outliers in the final refinement step. You may try removing the outliers by hard thresholding just like RANSAC, or implement the Cauchy kernel which works like soft thresholding (I recommend the former which is easier and more efficient).
> 
> Hi, amazing work! I want to know whether you don't filter any outliers to achieve a differentiable process for a end-to-end trianing manner.

Yes, we don't do any filtering during end-to-end training so that it is fully differentiable

**Comment by dazaier** [comment]
> Hi, Thanks for your kindly help~ I will have a try on removing the outliers.

你好，请问你最后尝试的结果有成功吗？我现在也想用Epro-Pnp替换opencv自带的solvePnP,因为opencv耗时比较久，但是看你的描述，会使得精度下降，能麻烦告知下你最后尝试的结果吗，感激不尽！
