### ISSUE TITLE
关于论文中3.1节的公式3

### ISSUE THREAD

**Issue by tangsipeng** [tjiiv-cprg/EPro-PnP#7]
你好，感谢开源。
请教一个论文中3.1节公式3的问题
根据条件概率公式展开后，为什么分子和分母中的 p(y) 可以隐去？

![20220627164728](https://user-images.githubusercontent.com/4188431/175898988-5cc26228-a5dd-44e2-a9a3-5c9218b60757.png)

**Comment by Lakonik** [comment]
In our case, as we don't make any assumptions on the pose, we use an uninformative prior, or a flat prior.

**Comment by tangsipeng** [comment]
> In our case, as we don't make any assumptions on the pose, we use an uninformative prior, or a flat prior.

got it , thanks
