### ISSUE TITLE
Question regarding batch size

### ISSUE THREAD

**Issue by harsanyidani** [tjiiv-cprg/EPro-PnP#73]
Hi!
I'm using 1 GPU for training and I'm trying to figure out what is my batch size and how can I modify it.

In the readme of EPro-PnP-Det:
_Note that the total batch size is determined by the number of GPUs you specified. For EPro-PnP-Det v1 we use 4 GPUs, each processing 3 images. For EPro-PnP-Det v1b we use 2 GPUs, each processing 6 images. For these configurations we recommend GPUs with at least 24 GB of VRAM. You may edit the samples_per_gpu option in the config file to vary the number of images per GPU._

In this context what counts as a sample? A single image? I'm a bit confused because in the nuscenes dataset thera are 6 images for a sample. How can I set my batch size with the samples_per_gpu parameter?

**Comment by Lakonik** [comment]
sample refers to a single image. In EPro-PnP-Det v1b, each GPU loads 6 images, so the total batch size is 12

**Comment by harsanyidani** [comment]
Thanks for the quick answer! 

But now I have more questions regarding this topic:
I'm using the epropnp_det_basic config with 1 Tesla T4 16GB GPU on nuscenes full dataset. I've tried with setting the samples_per_gpu parameter to 3 (original in repo) and 2. So If I understood your reply correctly that means batch size 2 and 3 in my case because I only have 1 GPU.

- When trying with the parameter set to 3, in the logs I see that 1 epoch is 554 iterations (e.g. Epoch [1][20/554] ...).

- With 2 as the parameter, the number of iterations is 831.

I don't understand what these number come from because int the full nuscenes training set there are 700 scenes, in each scene there are 40 keyframes (2 Hz sampling) and there are 6 images in each keyframe. Thats about 168000 images. If I count with batch size 3, thats 56000 iterations per epoch so one of the numbers is wrong. Please help me understand this.

Thanks in advance!

**Comment by Lakonik** [comment]
yeah there should be much more iterations than 831... Are you using the full nuscenes set (not the mini set)?

**Comment by harsanyidani** [comment]
Yes, I think. In my directory EPro-PnP-Det/data/nuscenes directory I have the samples directory with 34149 images in each camera driectory. I also have the v1.0-mini and v1.0-trainval folders. First I only trained on the mini dataset so only preprocessed the v1.0-mini with _tools/data_converter/nuscenes_converter.py data/nuscenes --version v1.0-mini_. After that I also did this with the v1.0-trainval. Now I have the two .pkl files (train and val). Did I do something wrong?

**Comment by Lakonik** [comment]
> Yes, I think. In my directory EPro-PnP-Det/data/nuscenes directory I have the samples directory with 34149 images in each camera driectory. I also have the v1.0-mini and v1.0-trainval folders. First I only trained on the mini dataset so only preprocessed the v1.0-mini with _tools/data_converter/nuscenes_converter.py data/nuscenes --version v1.0-mini_. After that I also did this with the v1.0-trainval. Now I have the two .pkl files (train and val). If I see it correctly there's no option in the training script to specify which dataset to train on and the script uses the pkl file in the nuscenes directory. Did I do something wrong?
> 
> I attached the pkl file for training: [nuscenes_annotations_train.zip](https://github.com/tjiiv-cprg/EPro-PnP/files/11603158/nuscenes_annotations_train.zip)

it looks like this .pkl is not the full training set. please try deleting this .pkl and run v1.0-trainval preprocessing again

**Comment by harsanyidani** [comment]
Yes, I see the problem now, the process always gets killed near the end:

Out of memory: Killed process 1430181 (python) total-vm:23905624kB, anon-rss:14159216kB, file-rss:4kB, shmem-rss:0kB, UID:0 pgtables:29404kB oom_score_adj:0

I'm running everything in a docker container.

I'm trying to disable OOM but it seems like the process consumes way too much memory. Or is this normal and I just need more memory?

**Comment by harsanyidani** [comment]
I managed to do the preprocess, I had to allocate more swap memory beacuse there is a huge spike in memory usage when writing the annotations to pickle files.
Now training on the full dataset with batch size one there are 135541 iterations/epoch which is much more beliveable. But I still don't understand that number, because as I explained in a previous comment 
>  in the full nuscenes training set there are 700 scenes, in each scene there are 40 keyframes (2 Hz sampling) and there are 6 images in each keyframe. Thats about 168000 images. 

So there are around 32000 images missing. What's the explanation for this? Are they get filtered aout during the preprocessing? If so, can you point me where exactly? (I couldn't find it.)

Thanks in advance for your answer!

**Comment by Lakonik** [comment]
Images with no objects are ignored during training
https://github.com/tjiiv-cprg/EPro-PnP/blob/5ee1525e2822517e4a6909859ea6a4d1daa032b7/EPro-PnP-Det/epropnp_det/datasets/nuscenes3d_dataset.py#L141-L149

**Comment by harsanyidani** [comment]
Thanks a lot!
