### ISSUE TITLE
A quick question about pose ambiguity

### ISSUE THREAD

**Issue by ZhiyLiu** [tjiiv-cprg/EPro-PnP#8]
Hi, when I read the paper, I got intuition saying: pose ambiguity can be handled by multiple modes learned by the model. However, right after that intuition, you said that: empirically, Dirac-like distribution works best, resulting in the simplified KL-divergence as eq (5). 

How to understand the intuition and the empirical finding?

Thanks,

**Comment by Lakonik** [comment]
Ambiguity and Dirac target are not contradictory. Dirac-like distribution works best as the target distribution. However, unless the model strongly overfits the data, usually it predicts a distribution with a lot of uncertainty. This is called the aleatoric uncertainty which reflects the noisy mapping from data to annotation that the model cannot overfit. So for symmetric objects and uncertain observations (e.g. when you can't decide whether a distant pedestrian is facing forward or backward), stochastically you have a target distribution composed of multiple peaks, and that's what the model actually learns.

**Comment by ZhiyLiu** [comment]
Thanks very much for the reply. Let's focus on the first term in eq (5) only. Supposing a symmetric object have forward and backward ambiguity as you mentioned, is the y_gt characterizing the true pose of forward or backward?

**Comment by Lakonik** [comment]
For a single object y_gt is either forward or backward. For multiple symmetric objects though, it is a matter of randomness, and if the annotation is not biased towards a certain direction, then 50% are forward and 50% are backward. If the model cannot overfit such randomness, it will treat all these objects as if they were annotated with both directions the same time.

Alternatively, you can actually assign ambiguous targets (mixture of multiple Dirac-like distributions) during training, although we doubt if it is necessary at all.
