### ISSUE TITLE
Theoretical question about Importance-sampling

### ISSUE THREAD

**Issue by harsanyidani** [tjiiv-cprg/EPro-PnP#82]
This is not a code-related question but I thought I could ask it here. 
I don't understand the equation for vanilla importance-sampling in your paper.
I asked the specific question on cross-validated:

[QUESTION](https://stats.stackexchange.com/questions/627710/monte-carlo-integration-with-importance-sampling-in-a-specific-case)

I would be very grateful if someone could answer it here or there. 
Thanks in advance!

**Comment by Lakonik** [comment]
Answered in https://github.com/tjiiv-cprg/EPro-PnP-v2/issues/3
